steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'NEXT_PUBLIC_CONVEX_URL=https://sensible-clam-597.eu-west-1.convex.cloud'
      - '--build-arg'
      - 'NEXT_PUBLIC_CONVEX_SITE_URL=https://sensible-clam-597.eu-west-1.convex.site'
      - '-t'
      - 'gcr.io/digitalium-ga/agasa-pro'
      - '.'

images:
  - 'gcr.io/digitalium-ga/agasa-pro'

timeout: '1200s'
